version: '3.1'

services:
  www:
    build:
      context: "."
      dockerfile: "Dockerfile"
    #    environment:
    volumes:
      - .:/home/elixir/app
    ports:
      - "8080:8080"
      - "4001:4001"
