name: checks

on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - run: yarn install --frozen-lockfile
      - run: yarn lint:ci

      - uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,ref,workflow,job
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL_CI }}
        if: failure()

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - run: yarn install --frozen-lockfile

      - env:
          GITHUB_ORGS_ALL_REPOS: holochain
          MAX_DAYS_SINCE_LAST_PUSH: 180
          MAX_REPOS: 2
          PUBLIC_REPOS_GITHUB_ACCESS_TOKEN: ${{ secrets.PUBLIC_REPOS_GITHUB_ACCESS_TOKEN }}
          UPDATE_EXISTING_REPOS: false
        run: yarn build

      - uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,ref,workflow,job
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL_CI }}
        if: failure()
